/** 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * SlimHorizContentPane.java
 *
 * Created on den 30 juli 2007, 14:39
 */

package com.lfv.lanzius.application.slim;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author  Andreas
 */
public class SlimHorizContentPane extends javax.swing.JPanel implements SlimContentPane {

    /** Creates new form SlimHorizContentPane */
    public SlimHorizContentPane() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Radio"));

        jComboBox1.setFocusable(false);
        jComboBox1.setPreferredSize(new java.awt.Dimension(140, 20));
        jPanel1.add(jComboBox1);

        jButton1.setBackground(java.awt.Color.lightGray);
        jButton1.setText("RXTX");
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jPanel1.add(jButton1);

        jButton2.setBackground(java.awt.Color.lightGray);
        jButton2.setText("BUSY");
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jPanel1.add(jButton2);

        jButton3.setBackground(java.awt.Color.lightGray);
        jButton3.setText("TALK");
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jPanel1.add(jButton3);

        add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone"));

        jComboBox2.setFocusable(false);
        jComboBox2.setPreferredSize(new java.awt.Dimension(120, 20));
        jPanel2.add(jComboBox2);

        jComboBox3.setFocusable(false);
        jComboBox3.setPreferredSize(new java.awt.Dimension(120, 20));
        jPanel2.add(jComboBox3);

        jButton4.setBackground(java.awt.Color.lightGray);
        jButton4.setText("DIAL");
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jPanel2.add(jButton4);

        jButton6.setBackground(java.awt.Color.lightGray);
        jButton6.setText("INTERPHONE");
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jPanel2.add(jButton6);

        add(jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Settings"));

        jButton5.setBackground(java.awt.Color.lightGray);
        jButton5.setText("SETTINGS");
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jPanel4.add(jButton5);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabel1.setForeground(java.awt.Color.red);
        jPanel4.add(jLabel1);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox getRadioComboBox() {
        return jComboBox1;
    }

    public JButton getStateButton() {
        return jButton1;
    }

    public JButton getBusyButton() {
        return jButton2;
    }

    public JButton getTalkButton() {
        return jButton3;
    }

    public JButton getSettingsButton() {
        return jButton5;
    }

    public JComboBox getRoleComboBox() {
        return jComboBox2;
    }

    public JComboBox getPeerComboBox() {
        return jComboBox3;
    }

    public JButton getDialButton() {
        return jButton4;
    }

    public JButton getHookButton() {
        return jButton6;
    }

    public JLabel getStatusLabel() {
        return jLabel1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

}
